version: 2.1

jobs:
  test:
    docker:
      - image: 'circleci/node:12.18'
    steps:
      - checkout
      - run:
          name: update-npm
          command: sudo npm install -g npm@latest
      - run:
          name: Install node modules
          command: npm ci
      - run:
          name: test
          command: npm test
workflows:
  version: 2.1
  test_and_build:
    jobs:
      - test